# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'Stress' do
    pod 'AVOSCloud'
    pod 'AFSoundManager'
end

target 'StressTests' do

end

target 'StressUITests' do

end

